### ISSUE TITLE
Python Agent not running

### ISSUE THREAD

**Issue by schererl** [Ludeme/LudiiPythonAI#1]
Hey, I followed the steps to use the Python Agent code and is something wrong.

I already compiled jpy and moved to \lib the  *.so files, jpy-0.10.0-SNAPSHOT.jar and .properties modifying the directories as it is asked to do.

Im trying to run Ludi programatically (instantiating the pythonAgent before running Ludii using AiRegistry.registerAI(..)) and after start the game and set the external agent, when the Python Agent have to make a move it throws an exception.

Here is two screenshots with the exception and .properties file:
![Screenshot from 2022-03-23 16-46-16](https://user-images.githubusercontent.com/19625890/159783347-d40fec50-81e7-439e-8d8d-b1f205d24ec5.png)
![Screenshot from 2022-03-23 16-46-38](https://user-images.githubusercontent.com/19625890/159783354-ce3a1c26-7bdb-40ea-8474-c31e45efe2b4.png)

**Comment by DennisSoemers** [comment]
Based on the stacktrace that looks to me like it's purely an issue with getting `jpy` to load correctly, nothing specific to Ludii.

Would it be possible for you to also show me what your code inside `LudiiPythonAI.java` looks like? Is it still similar to our example? In particular, does it still call `System.setProperty()` as is done in line 85 of our example [here](https://github.com/Ludeme/LudiiPythonAI/blob/df9d5f16a8c8eb33378b0809d5c764f1fa7943ec/src/ludii_python_ai/LudiiPythonAI.java#L85)?

A quick google search for that error led to the following issue from some other repo that also uses jpy, maybe this is of any help to you: https://github.com/bcdev/jpy/issues/95 ?
