### ISSUE TITLE
Uct algorithm Bug 

### ISSUE THREAD

**Issue by Sidahmed-ben** [Ludeme/LudiiPythonAI#2]
Hello @DennisSoemers, i found a bug in UCT algorithm, exactly  here : https://github.com/Ludeme/LudiiPythonAI/blob/df9d5f16a8c8eb33378b0809d5c764f1fa7943ec/ludii_python/uct.py#L143.
This loop allows to save the score of each node after Rollout , but  it saves only the score for first players and not the last player, which does not allow to the last player to use the IA. 
For example if the game has 4 players, the score is saved for the three first player and not for  the fourth.
To solve this we must add (+1) inside the range of the loop, that allows to save the score of the last player and to use the IA for him. 
I tested this and it works fine 👍

**Comment by DennisSoemers** [comment]
Yep, you're correct. Fixed by #3
